spring.application.name=eggtec

# database connect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:handalab}
spring.datasource.password=${DB_PASSWORD:handalab}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eggtec}

# HikariCP connection pool setting
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# timeout
spring.datasource.hikari.connection-timeout=10000

# MyBatis setting
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=com.example.demo.domain

# MyBatis additional setting
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.cache-enabled=false

# jackson - cammel case to snake case
spring.jackson.property-naming-strategy=SNAKE_CASE

# error stacktrace print X
server.error.include-stacktrace=never

# import .env file
spring.config.import=optional:file:.env[.properties]

# socket.io ports
socketio.server.port = 4001,4002,4003,4005,4006
socketio.server.port.interval = 4004
socketio.server.port.nojson = 4005,4006

# logback
# log.config.path=/var/log
# log.config.filename=console
# error.log.config.filename=error
log.config.path=C:/logs/myapp
log.config.filename=app
error.log.config.filename=app-error